version: '3.9'

services:
  backend:
    image: telequest:latest
    env_file: 
      - .env
    command: python app.py
    networks:
      - app-network

  frontend:
    image: telequest:latest
    env_file: 
      - .env
    working_dir: /app/web
    command: npx serve -s build -l 3000
    networks:
      - app-network
    ports:
      - "3000:3000"

networks:
  app-network:
