name: Mypy Checks, Black Formatting and Pylint Checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install -r py-requirements.txt
    - run: pip install "black<23"
    - run: black --diff --check $(git ls-files '*.py')
    - run: mypy --explicit-package-bases --install-types  --non-interactive  --cache-dir=.mypy_cache/ --strict $(git ls-files '*.py')  --disable-error-code name-match --disable-error-code no-redef --disable-error-code unused-ignore
