name: Python Unittests with Coverage

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Set Environment Variables
      run: |
        echo "DB_NAME=telequest" >> $GITHUB_ENV
        echo "BOT_TOKEN=bot_token_key" >> $GITHUB_ENV
        echo "MONGO_URI=mongo_db_key" >> $GITHUB_ENV
        echo "PINECONE_KEY=your_pinecone_key" >> $GITHUB_ENV
        echo "PINECONE_ENV=your_pinecone_env" >> $GITHUB_ENV
        echo "ENVIRONMENT=TEST" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install coverage
        pip install -r mypy-requirements.txt

    - name: Run unittests with coverage
      run: |
          COVERAGE_DATA_COLLECTED=0
          coverage run -m unittest discover ai || true
          [ $? -eq 0 ] && COVERAGE_DATA_COLLECTED=1
          coverage run -m unittest discover bot || true
          [ $? -eq 0 ] && COVERAGE_DATA_COLLECTED=1
          coverage run -m unittest discover db || true
          [ $? -eq 0 ] && COVERAGE_DATA_COLLECTED=1
          echo "COVERAGE_DATA_COLLECTED=$COVERAGE_DATA_COLLECTED" >> $GITHUB_ENV
          coverage report -m || true
          coverage xml || true