name: Python Unittests with Coverage

on: [pull_request]

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.x'
      
    - name: Set Environment Variables
      run: |
        echo "DB_NAME=telequest" >> $GITHUB_ENV
        echo "BOT_TOKEN=bot_token_key" >> $GITHUB_ENV
        echo "LOCAL_BOT_TOKEN=local_bot_token_key" >> $GITHUB_ENV
        echo "MONGO_URI=mongo_db_key" >> $GITHUB_ENV
        echo "PINECONE_KEY=your_pinecone_key" >> $GITHUB_ENV
        echo "PINECONE_ENV=your_pinecone_env" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=your_openai_key" >> $GITHUB_ENV
        echo "ENVIRONMENT=TEST" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install coverage
        pip install -r mypy-requirements.txt

    - name: Run unittests with coverage
      run: |
        coverage run -m unittest discover
        coverage report -m
